// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pitaya.proto

#include "pitaya.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protos {
}  // namespace protos
namespace protobuf_pitaya_2eproto {
void InitDefaults() {
}

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "pitaya.proto", schemas, file_default_instances, TableStruct::offsets,
      NULL, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014pitaya.proto\022\006protos\032\rrequest.proto\032\016r"
      "esponse.proto\032\npush.proto\032\nbind.proto\032\nk"
      "ick.proto2\322\001\n\006Pitaya\022+\n\004Call\022\017.protos.Re"
      "quest\032\020.protos.Response\"\000\022.\n\nPushToUser\022"
      "\014.protos.Push\032\020.protos.Response\"\000\0228\n\021Ses"
      "sionBindRemote\022\017.protos.BindMsg\032\020.protos"
      ".Response\"\000\0221\n\010KickUser\022\017.protos.KickMsg"
      "\032\022.protos.KickAnswer\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 310);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pitaya.proto", &protobuf_RegisterTypes);
  ::protobuf_request_2eproto::AddDescriptors();
  ::protobuf_response_2eproto::AddDescriptors();
  ::protobuf_push_2eproto::AddDescriptors();
  ::protobuf_bind_2eproto::AddDescriptors();
  ::protobuf_kick_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_pitaya_2eproto
namespace protos {

// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
