// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protodescriptor.proto

#include "protodescriptor.pb.h"
#include "protodescriptor.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace protos {

} // namespace protos

